Fix `skipTest` inside `subTest`
pytest-dev/pytest-subtests pull request #169
Opened 2024-11-18 13:45 UTC by ydshieh

Currently, the reporting has issues in the cases where `skipTest` is used inside `subTest`. For example

```python
import unittest

class T(unittest.TestCase):
    def test_foo(self):
        for i in range(10):
            with self.subTest("custom message", i=i):
                if i < 4:
                    self.skipTest(f"skip {i}")
                assert i < 4
```
outputs
```bash
tests/test_foo.py::T::test_foo [custom message] (i=4) SUBSKIP (skip 0)
tests/test_foo.py::T::test_foo [custom message] (i=5) SUBSKIP (skip 1)
tests/test_foo.py::T::test_foo [custom message] (i=6) SUBSKIP (skip 2)
tests/test_foo.py::T::test_foo [custom message] (i=7) SUBSKIP (skip 3)
tests/test_foo.py::T::test_foo [custom message] (i=8) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=9) SUBFAIL
tests/test_foo.py::T::test_foo PASSED
...
=============== short test summary info ===============
[custom message] (i=8) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 8 < 4
[custom message] (i=9) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 9 < 4
=============== 2 failed, 1 passed, 4 skipped in 0.15s  =============== 
```
which is obviously wrong.

This PR fix the above issue. The new output is

```bash
tests/test_foo.py::T::test_foo [custom message] (i=0) SUBSKIP (skip 0)
tests/test_foo.py::T::test_foo [custom message] (i=1) SUBSKIP (skip 1)
tests/test_foo.py::T::test_foo [custom message] (i=2) SUBSKIP (skip 2)
tests/test_foo.py::T::test_foo [custom message] (i=3) SUBSKIP (skip 3)
tests/test_foo.py::T::test_foo [custom message] (i=4) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=5) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=6) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=7) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=8) SUBFAIL
tests/test_foo.py::T::test_foo [custom message] (i=9) SUBFAIL
tests/test_foo.py::T::test_foo PASSED                                                                                                                                                                        
...
=============== short test summary info ===============
 [custom message] (i=4) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 4 < 4
[custom message] (i=5) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 5 < 4
[custom message] (i=6) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 6 < 4
[custom message] (i=7) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 7 < 4
[custom message] (i=8) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 8 < 4
[custom message] (i=9) SUBFAIL tests/test_foo.py::T::test_foo - AssertionError: assert 9 < 4
=============== 6 failed, 1 passed, 4 skipped in 0.20s  =============== 
```

2024-11-18 13:56 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +    TestCaseFunction.addSkip = _addSkip  # type: ignore[attr-defined]
The `_addSkip` in `unittest.case` doesn't contain logic to call `addSubTest` for `outcome.skipped` (unlike `_feedErrorsToResult`), and it turns out this causes the reporting issue described in the PR.

Unlike `addSubTest` (where original `TestCaseFunction` doesn't have it), `addSkip` is defined `TestCaseFunction`, and here we save the original implementation and patch `TestCaseFunction.addSkip` to a newly defined `_addSkip` that allows us to call `addSubTest`.

The `_originaladdSkip` allows us to restore to it in `pytest_unconfigure` as well as it turns out necessary to call it too inside the newly defined `_addSkip`.

2024-11-18 17:05 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +            self._originaladdSkip(testcase, reason)
If we have `skipTest` outside a `subTest` and there are some subtest failures, this has to be done in this way here to make the reporting results correct.

2024-11-18 17:06 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +
ugly though. Happy to change if there is a better solution.

2024-11-18 17:52 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +    TestCaseFunction.addSkip = _addSkip  # type: ignore[method-assign]
The `_addSkip` in `unittest.case` doesn't contain logic to call `addSubTest` for `outcome.skipped` (unlike `_feedErrorsToResult`), and it turns out this causes the reporting issue described in the PR.

Unlike `addSubTest` (where original `TestCaseFunction` doesn't have it), `addSkip` is defined `TestCaseFunction`, and here we save the original implementation and patch `TestCaseFunction.addSkip` to a newly defined `_addSkip` that allows us to call `addSubTest`.

The `_originaladdSkip` allows us to restore to it in `pytest_unconfigure` as well as it turns out necessary to call it too inside the newly defined `_addSkip`.

2024-11-18 17:53 UTC, dvrogozh commented
> tests/test_foo.py::T::test_foo PASSED

Why the whole test is marked as passed if all subtests either failed or skipped? or we need to consider that there might be a testing code in the test out of subtest code? If so, I wish for documentation example for that with description.

I also wonder how python unittest reports such failures? is pytest-subtests behavior aligned?

2024-11-18 17:54 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +        self._originaladdSkip(testcase, reason)  # type: ignore[attr-defined]
In both case (subTest or not), we all need to call the original addSkip otherwise the reporting is still wrong.

2024-11-18 17:55 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +            self._originaladdSkip(testcase, reason)  # type: ignore[attr-defined]
If we have skipTest outside a subTest and there are some subtest failures, this has to be done in this way here to make the reporting results correct.

2024-11-18 17:56 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +                    self._originaladdSkip(testcase, reason)  # type: ignore[attr-defined]
ugly though. Happy to change if there is a better solution.

2024-11-19 09:15 UTC, ydshieh commented
cc @nicoddemus

2024-11-20 14:16 UTC, nicoddemus requested changes
Hi @ydshieh thanks for the PR

Other than my comments, we need a test to ensure this does not regress in the future.

2024-11-20 14:16 UTC, nicoddemus commented on src/pytest_subtests/plugin.py
> +                ]
Please move this list comprehension to a variable so it reads better.

2024-11-20 19:59 UTC, ydshieh commented
> Hi @ydshieh thanks for the PR
> 
> Other than my comments, we need a test to ensure this does not regress in the future.

Good point! I will add some tests

2024-11-21 15:56 UTC, ydshieh commented on src/pytest_subtests/plugin.py
> +        if sys.version_info < (3, 11):
python unittest has some changes which leads to this if/else here

2024-12-04 19:51 UTC, ydshieh commented
Hi @nicoddemus Could you take a look for this new version 🙏 ? Thank you!

2024-12-04 20:13 UTC, nicoddemus commented
Hi @ydshieh, sorry for the delay here, indeed this PR went through the cracks.

I will review this weekend at the latest, and make a new release then. 👍

2024-12-05 08:47 UTC, ydshieh commented
No worry, it's normal (with so many notifications nowadays 😄). Thank you in advance.

2024-12-07 11:10 UTC, nicoddemus approved these changes
Thanks @ydshieh, LGTM!

I did tweak the tests a bit in order to pass on CI, and also added a CHANGELOG entry.

2024-12-07 11:14 UTC, merged